package cn.kane.quartz.admin.mapper;

import cn.kane.quartz.admin.domain.AdminTrigger;
import cn.kane.quartz.admin.domain.AdminTriggerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminTriggerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    int countByExample(AdminTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    int deleteByExample(AdminTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    int deleteByPrimaryKey(Long triggerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    int insert(AdminTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    int insertSelective(AdminTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    List<AdminTrigger> selectByExample(AdminTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    AdminTrigger selectByPrimaryKey(Long triggerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") AdminTrigger record, @Param("example") AdminTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    int updateByExample(@Param("record") AdminTrigger record, @Param("example") AdminTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    int updateByPrimaryKeySelective(AdminTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_TRIGGER
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    int updateByPrimaryKey(AdminTrigger record);
}