package cn.kane.quartz.admin.domain;

import java.util.ArrayList;
import java.util.List;

public class AdminJobExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public AdminJobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobidIsNull() {
            addCriterion("JOBID is null");
            return (Criteria) this;
        }

        public Criteria andJobidIsNotNull() {
            addCriterion("JOBID is not null");
            return (Criteria) this;
        }

        public Criteria andJobidEqualTo(Long value) {
            addCriterion("JOBID =", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotEqualTo(Long value) {
            addCriterion("JOBID <>", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidGreaterThan(Long value) {
            addCriterion("JOBID >", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidGreaterThanOrEqualTo(Long value) {
            addCriterion("JOBID >=", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidLessThan(Long value) {
            addCriterion("JOBID <", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidLessThanOrEqualTo(Long value) {
            addCriterion("JOBID <=", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidIn(List<Long> values) {
            addCriterion("JOBID in", values, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotIn(List<Long> values) {
            addCriterion("JOBID not in", values, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidBetween(Long value1, Long value2) {
            addCriterion("JOBID between", value1, value2, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotBetween(Long value1, Long value2) {
            addCriterion("JOBID not between", value1, value2, "jobid");
            return (Criteria) this;
        }

        public Criteria andScheduleridIsNull() {
            addCriterion("SCHEDULERID is null");
            return (Criteria) this;
        }

        public Criteria andScheduleridIsNotNull() {
            addCriterion("SCHEDULERID is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleridEqualTo(Long value) {
            addCriterion("SCHEDULERID =", value, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andScheduleridNotEqualTo(Long value) {
            addCriterion("SCHEDULERID <>", value, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andScheduleridGreaterThan(Long value) {
            addCriterion("SCHEDULERID >", value, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andScheduleridGreaterThanOrEqualTo(Long value) {
            addCriterion("SCHEDULERID >=", value, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andScheduleridLessThan(Long value) {
            addCriterion("SCHEDULERID <", value, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andScheduleridLessThanOrEqualTo(Long value) {
            addCriterion("SCHEDULERID <=", value, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andScheduleridIn(List<Long> values) {
            addCriterion("SCHEDULERID in", values, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andScheduleridNotIn(List<Long> values) {
            addCriterion("SCHEDULERID not in", values, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andScheduleridBetween(Long value1, Long value2) {
            addCriterion("SCHEDULERID between", value1, value2, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andScheduleridNotBetween(Long value1, Long value2) {
            addCriterion("SCHEDULERID not between", value1, value2, "schedulerid");
            return (Criteria) this;
        }

        public Criteria andJobnameIsNull() {
            addCriterion("JOBNAME is null");
            return (Criteria) this;
        }

        public Criteria andJobnameIsNotNull() {
            addCriterion("JOBNAME is not null");
            return (Criteria) this;
        }

        public Criteria andJobnameEqualTo(String value) {
            addCriterion("JOBNAME =", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotEqualTo(String value) {
            addCriterion("JOBNAME <>", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameGreaterThan(String value) {
            addCriterion("JOBNAME >", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameGreaterThanOrEqualTo(String value) {
            addCriterion("JOBNAME >=", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLessThan(String value) {
            addCriterion("JOBNAME <", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLessThanOrEqualTo(String value) {
            addCriterion("JOBNAME <=", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameLike(String value) {
            addCriterion("JOBNAME like", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotLike(String value) {
            addCriterion("JOBNAME not like", value, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameIn(List<String> values) {
            addCriterion("JOBNAME in", values, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotIn(List<String> values) {
            addCriterion("JOBNAME not in", values, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameBetween(String value1, String value2) {
            addCriterion("JOBNAME between", value1, value2, "jobname");
            return (Criteria) this;
        }

        public Criteria andJobnameNotBetween(String value1, String value2) {
            addCriterion("JOBNAME not between", value1, value2, "jobname");
            return (Criteria) this;
        }

        public Criteria andGroupIsNull() {
            addCriterion("GROUP is null");
            return (Criteria) this;
        }

        public Criteria andGroupIsNotNull() {
            addCriterion("GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andGroupEqualTo(String value) {
            addCriterion("GROUP =", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotEqualTo(String value) {
            addCriterion("GROUP <>", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupGreaterThan(String value) {
            addCriterion("GROUP >", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP >=", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupLessThan(String value) {
            addCriterion("GROUP <", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupLessThanOrEqualTo(String value) {
            addCriterion("GROUP <=", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupLike(String value) {
            addCriterion("GROUP like", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotLike(String value) {
            addCriterion("GROUP not like", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupIn(List<String> values) {
            addCriterion("GROUP in", values, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotIn(List<String> values) {
            addCriterion("GROUP not in", values, "group");
            return (Criteria) this;
        }

        public Criteria andGroupBetween(String value1, String value2) {
            addCriterion("GROUP between", value1, value2, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotBetween(String value1, String value2) {
            addCriterion("GROUP not between", value1, value2, "group");
            return (Criteria) this;
        }

        public Criteria andJobclassIsNull() {
            addCriterion("JOBCLASS is null");
            return (Criteria) this;
        }

        public Criteria andJobclassIsNotNull() {
            addCriterion("JOBCLASS is not null");
            return (Criteria) this;
        }

        public Criteria andJobclassEqualTo(String value) {
            addCriterion("JOBCLASS =", value, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassNotEqualTo(String value) {
            addCriterion("JOBCLASS <>", value, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassGreaterThan(String value) {
            addCriterion("JOBCLASS >", value, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassGreaterThanOrEqualTo(String value) {
            addCriterion("JOBCLASS >=", value, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassLessThan(String value) {
            addCriterion("JOBCLASS <", value, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassLessThanOrEqualTo(String value) {
            addCriterion("JOBCLASS <=", value, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassLike(String value) {
            addCriterion("JOBCLASS like", value, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassNotLike(String value) {
            addCriterion("JOBCLASS not like", value, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassIn(List<String> values) {
            addCriterion("JOBCLASS in", values, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassNotIn(List<String> values) {
            addCriterion("JOBCLASS not in", values, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassBetween(String value1, String value2) {
            addCriterion("JOBCLASS between", value1, value2, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobclassNotBetween(String value1, String value2) {
            addCriterion("JOBCLASS not between", value1, value2, "jobclass");
            return (Criteria) this;
        }

        public Criteria andJobdatamapIsNull() {
            addCriterion("JOBDATAMAP is null");
            return (Criteria) this;
        }

        public Criteria andJobdatamapIsNotNull() {
            addCriterion("JOBDATAMAP is not null");
            return (Criteria) this;
        }

        public Criteria andJobdatamapEqualTo(String value) {
            addCriterion("JOBDATAMAP =", value, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapNotEqualTo(String value) {
            addCriterion("JOBDATAMAP <>", value, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapGreaterThan(String value) {
            addCriterion("JOBDATAMAP >", value, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapGreaterThanOrEqualTo(String value) {
            addCriterion("JOBDATAMAP >=", value, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapLessThan(String value) {
            addCriterion("JOBDATAMAP <", value, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapLessThanOrEqualTo(String value) {
            addCriterion("JOBDATAMAP <=", value, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapLike(String value) {
            addCriterion("JOBDATAMAP like", value, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapNotLike(String value) {
            addCriterion("JOBDATAMAP not like", value, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapIn(List<String> values) {
            addCriterion("JOBDATAMAP in", values, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapNotIn(List<String> values) {
            addCriterion("JOBDATAMAP not in", values, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapBetween(String value1, String value2) {
            addCriterion("JOBDATAMAP between", value1, value2, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andJobdatamapNotBetween(String value1, String value2) {
            addCriterion("JOBDATAMAP not between", value1, value2, "jobdatamap");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDurabilityIsNull() {
            addCriterion("DURABILITY is null");
            return (Criteria) this;
        }

        public Criteria andDurabilityIsNotNull() {
            addCriterion("DURABILITY is not null");
            return (Criteria) this;
        }

        public Criteria andDurabilityEqualTo(Integer value) {
            addCriterion("DURABILITY =", value, "durability");
            return (Criteria) this;
        }

        public Criteria andDurabilityNotEqualTo(Integer value) {
            addCriterion("DURABILITY <>", value, "durability");
            return (Criteria) this;
        }

        public Criteria andDurabilityGreaterThan(Integer value) {
            addCriterion("DURABILITY >", value, "durability");
            return (Criteria) this;
        }

        public Criteria andDurabilityGreaterThanOrEqualTo(Integer value) {
            addCriterion("DURABILITY >=", value, "durability");
            return (Criteria) this;
        }

        public Criteria andDurabilityLessThan(Integer value) {
            addCriterion("DURABILITY <", value, "durability");
            return (Criteria) this;
        }

        public Criteria andDurabilityLessThanOrEqualTo(Integer value) {
            addCriterion("DURABILITY <=", value, "durability");
            return (Criteria) this;
        }

        public Criteria andDurabilityIn(List<Integer> values) {
            addCriterion("DURABILITY in", values, "durability");
            return (Criteria) this;
        }

        public Criteria andDurabilityNotIn(List<Integer> values) {
            addCriterion("DURABILITY not in", values, "durability");
            return (Criteria) this;
        }

        public Criteria andDurabilityBetween(Integer value1, Integer value2) {
            addCriterion("DURABILITY between", value1, value2, "durability");
            return (Criteria) this;
        }

        public Criteria andDurabilityNotBetween(Integer value1, Integer value2) {
            addCriterion("DURABILITY not between", value1, value2, "durability");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverIsNull() {
            addCriterion("SHOULDRECOVER is null");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverIsNotNull() {
            addCriterion("SHOULDRECOVER is not null");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverEqualTo(Integer value) {
            addCriterion("SHOULDRECOVER =", value, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverNotEqualTo(Integer value) {
            addCriterion("SHOULDRECOVER <>", value, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverGreaterThan(Integer value) {
            addCriterion("SHOULDRECOVER >", value, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverGreaterThanOrEqualTo(Integer value) {
            addCriterion("SHOULDRECOVER >=", value, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverLessThan(Integer value) {
            addCriterion("SHOULDRECOVER <", value, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverLessThanOrEqualTo(Integer value) {
            addCriterion("SHOULDRECOVER <=", value, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverIn(List<Integer> values) {
            addCriterion("SHOULDRECOVER in", values, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverNotIn(List<Integer> values) {
            addCriterion("SHOULDRECOVER not in", values, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverBetween(Integer value1, Integer value2) {
            addCriterion("SHOULDRECOVER between", value1, value2, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andShouldrecoverNotBetween(Integer value1, Integer value2) {
            addCriterion("SHOULDRECOVER not between", value1, value2, "shouldrecover");
            return (Criteria) this;
        }

        public Criteria andTriggercountIsNull() {
            addCriterion("TRIGGERCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTriggercountIsNotNull() {
            addCriterion("TRIGGERCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTriggercountEqualTo(Integer value) {
            addCriterion("TRIGGERCOUNT =", value, "triggercount");
            return (Criteria) this;
        }

        public Criteria andTriggercountNotEqualTo(Integer value) {
            addCriterion("TRIGGERCOUNT <>", value, "triggercount");
            return (Criteria) this;
        }

        public Criteria andTriggercountGreaterThan(Integer value) {
            addCriterion("TRIGGERCOUNT >", value, "triggercount");
            return (Criteria) this;
        }

        public Criteria andTriggercountGreaterThanOrEqualTo(Integer value) {
            addCriterion("TRIGGERCOUNT >=", value, "triggercount");
            return (Criteria) this;
        }

        public Criteria andTriggercountLessThan(Integer value) {
            addCriterion("TRIGGERCOUNT <", value, "triggercount");
            return (Criteria) this;
        }

        public Criteria andTriggercountLessThanOrEqualTo(Integer value) {
            addCriterion("TRIGGERCOUNT <=", value, "triggercount");
            return (Criteria) this;
        }

        public Criteria andTriggercountIn(List<Integer> values) {
            addCriterion("TRIGGERCOUNT in", values, "triggercount");
            return (Criteria) this;
        }

        public Criteria andTriggercountNotIn(List<Integer> values) {
            addCriterion("TRIGGERCOUNT not in", values, "triggercount");
            return (Criteria) this;
        }

        public Criteria andTriggercountBetween(Integer value1, Integer value2) {
            addCriterion("TRIGGERCOUNT between", value1, value2, "triggercount");
            return (Criteria) this;
        }

        public Criteria andTriggercountNotBetween(Integer value1, Integer value2) {
            addCriterion("TRIGGERCOUNT not between", value1, value2, "triggercount");
            return (Criteria) this;
        }

        public Criteria andJobstatusIsNull() {
            addCriterion("JOBSTATUS is null");
            return (Criteria) this;
        }

        public Criteria andJobstatusIsNotNull() {
            addCriterion("JOBSTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andJobstatusEqualTo(Integer value) {
            addCriterion("JOBSTATUS =", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotEqualTo(Integer value) {
            addCriterion("JOBSTATUS <>", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusGreaterThan(Integer value) {
            addCriterion("JOBSTATUS >", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("JOBSTATUS >=", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusLessThan(Integer value) {
            addCriterion("JOBSTATUS <", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusLessThanOrEqualTo(Integer value) {
            addCriterion("JOBSTATUS <=", value, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusIn(List<Integer> values) {
            addCriterion("JOBSTATUS in", values, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotIn(List<Integer> values) {
            addCriterion("JOBSTATUS not in", values, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusBetween(Integer value1, Integer value2) {
            addCriterion("JOBSTATUS between", value1, value2, "jobstatus");
            return (Criteria) this;
        }

        public Criteria andJobstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("JOBSTATUS not between", value1, value2, "jobstatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 21 14:33:05 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QUARTZ_ADMIN_JOB
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}