package cn.kane.quartz.admin.domain;

public class AdminTrigger {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_TRIGGER.TRIGGERID
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private Long triggerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_TRIGGER.JOBID
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private Long jobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_TRIGGER.NAME
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_TRIGGER.DESCRIPTION
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_TRIGGER.GROUP
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private String group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_TRIGGER.CRONEXPR
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private String cronexpr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_TRIGGER.TRIGGERID
     *
     * @return the value of QUARTZ_ADMIN_TRIGGER.TRIGGERID
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public Long getTriggerid() {
        return triggerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_TRIGGER.TRIGGERID
     *
     * @param triggerid the value for QUARTZ_ADMIN_TRIGGER.TRIGGERID
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setTriggerid(Long triggerid) {
        this.triggerid = triggerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_TRIGGER.JOBID
     *
     * @return the value of QUARTZ_ADMIN_TRIGGER.JOBID
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public Long getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_TRIGGER.JOBID
     *
     * @param jobid the value for QUARTZ_ADMIN_TRIGGER.JOBID
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setJobid(Long jobid) {
        this.jobid = jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_TRIGGER.NAME
     *
     * @return the value of QUARTZ_ADMIN_TRIGGER.NAME
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_TRIGGER.NAME
     *
     * @param name the value for QUARTZ_ADMIN_TRIGGER.NAME
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_TRIGGER.DESCRIPTION
     *
     * @return the value of QUARTZ_ADMIN_TRIGGER.DESCRIPTION
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_TRIGGER.DESCRIPTION
     *
     * @param description the value for QUARTZ_ADMIN_TRIGGER.DESCRIPTION
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_TRIGGER.GROUP
     *
     * @return the value of QUARTZ_ADMIN_TRIGGER.GROUP
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_TRIGGER.GROUP
     *
     * @param group the value for QUARTZ_ADMIN_TRIGGER.GROUP
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setGroup(String group) {
        this.group = group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_TRIGGER.CRONEXPR
     *
     * @return the value of QUARTZ_ADMIN_TRIGGER.CRONEXPR
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public String getCronexpr() {
        return cronexpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_TRIGGER.CRONEXPR
     *
     * @param cronexpr the value for QUARTZ_ADMIN_TRIGGER.CRONEXPR
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setCronexpr(String cronexpr) {
        this.cronexpr = cronexpr;
    }
}