package cn.kane.quartz.admin.domain;

import java.io.Serializable;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class AdminScheduler implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3238947873241631740L;
	
	public AdminScheduler(){
		
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_SCHEDULER.SCHEDULERID
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private Long schedulerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_SCHEDULER.NAME
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_SCHEDULER.HOST
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_SCHEDULER.PORT
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_SCHEDULER.USERNAME
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUARTZ_ADMIN_SCHEDULER.PASSWORD
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_SCHEDULER.SCHEDULERID
     *
     * @return the value of QUARTZ_ADMIN_SCHEDULER.SCHEDULERID
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public Long getSchedulerid() {
        return schedulerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_SCHEDULER.SCHEDULERID
     *
     * @param schedulerid the value for QUARTZ_ADMIN_SCHEDULER.SCHEDULERID
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setSchedulerid(Long schedulerid) {
        this.schedulerid = schedulerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_SCHEDULER.NAME
     *
     * @return the value of QUARTZ_ADMIN_SCHEDULER.NAME
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_SCHEDULER.NAME
     *
     * @param name the value for QUARTZ_ADMIN_SCHEDULER.NAME
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_SCHEDULER.HOST
     *
     * @return the value of QUARTZ_ADMIN_SCHEDULER.HOST
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_SCHEDULER.HOST
     *
     * @param host the value for QUARTZ_ADMIN_SCHEDULER.HOST
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_SCHEDULER.PORT
     *
     * @return the value of QUARTZ_ADMIN_SCHEDULER.PORT
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_SCHEDULER.PORT
     *
     * @param port the value for QUARTZ_ADMIN_SCHEDULER.PORT
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_SCHEDULER.USERNAME
     *
     * @return the value of QUARTZ_ADMIN_SCHEDULER.USERNAME
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_SCHEDULER.USERNAME
     *
     * @param username the value for QUARTZ_ADMIN_SCHEDULER.USERNAME
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUARTZ_ADMIN_SCHEDULER.PASSWORD
     *
     * @return the value of QUARTZ_ADMIN_SCHEDULER.PASSWORD
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUARTZ_ADMIN_SCHEDULER.PASSWORD
     *
     * @param password the value for QUARTZ_ADMIN_SCHEDULER.PASSWORD
     *
     * @mbggenerated Wed Jan 21 14:33:05 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Override
    public String toString(){
    	return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
}